#!/bin/sh

set -e
exec </dev/null >&2

# Copy the kernel image, config, system map, and initramfs over to the netboot
# filesystem.

VERSION="$1"
NETBOOTDIR="/boot/netboot"

msg_err() {
	echo >&2 "E: cluster-netboot: $1"
	exit $2
}

msg_info() {
	echo >&2 "I: cluster-netboot: $1"
}

if ! [ -d "${NETBOOTDIR}" ]; then
	# Violating Debian kernel hook guidelines for bootloaders (sec 8.2 in the
	# Debian Linux Kernel Handbook) by exiting with a non-0 status when the
	# bootloader is "disabled". In this case, I *want* to be alerted that the
	# "bootloader" isn't being updated properly.
	msg_err "/boot/netboot is not mounted" 3
fi

if [ -z "${VERSION}" ]; then
	msg_err "No kernel version given" 2
fi

# Cribbed from the initramfs-tools postinst script.
# This avoids running the script mutliple times (see Debian Policy manual 
# section 6.5 for the various arguments a postrm script can be given).
if [ -n "$DEB_MAINT_PARAMS" ]; then
	# This will clobber the old script parameters, but that's alright as they're
	# already saved.
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

# Have to put the dpkg arch in here as Ubuntu uses a "generic" kernel for 32 and
# 64 bit ARM.
KERNELDIR="${NETBOOTDIR}/kernel-${VERSION}-${DPKG_MAINTSCRIPT_ARCH}"

mkdir -p "${KERNELDIR}"
# There's an optional second argument with a path to the kernel. If it's not
# given, the path is either /boot/vmlinuz-$VERSION or /boot/vmlinux-$VERSION
# For our arches, it's vmlinuz
if [ -z "$2" ]; then
	BOOTDIR="/boot"
	if [ -e "${BOOTDIR}/vmlinuz-${VERSION}" ]; then
		KERNELFILE="${BOOTDIR}/vmlinuz-${VERSION}"
	else
		msg_err "Unable to find kernel at ${BOOTDIR}/vmlinuz-${VERSION}" 4
	fi
else
	BOOTDIR="$(dirname $2)"
	KERNELFILE="$2"
fi
CONFIGFILE="${BOOTDIR}/config-${VERSION}"
MAPFILE="${BOOTDIR}/System.map-${VERSION}"
INITRAMFS="${BOOTDIR}/initrd.img-${VERSION}"

msg_info "Installing ${KERNELFILE} to ${KERNELDIR}/vmlinuz"
cp -f "${KERNELFILE}" "${KERNELDIR}/vmlinuz"
msg_info "Installing ${MAPFILE} to ${KERNELDIR}/System.map"
cp -f "${MAPFILE}" "${KERNELDIR}/System.map"
msg_info "Installing ${CONFIGFILE} to ${KERNELDIR}/config"
cp -f "${CONFIGFILE}" "${KERNELDIR}/config"
msg_info "Installing ${INITRAMFS} to ${KERNELDIR}/initrd.img"
cp -f "${INITRAMFS}" "${KERNELDIR}/initrd.img"

DEVICE_TREE_DIR="/usr/lib/linux-image-${VERSION}"
# Ubuntu uses a different directory for its device trees
if ! [ -d "$DEVICE_TREE_DIR" ]; then
	if [ -d "/usr/lib/firmware/${VERSION}/device-tree" ]; then
		DEVICE_TREE_DIR="/usr/lib/firmware/${VERSION}/device-tree"
	fi
fi

PATTERNS_DIR="cluster-netboot/dtb-patterns"
DTBS_PATTERNS="/etc/${PATTERNS_DIR}/${DPKG_MAINTSCRIPT_ARCH}"
if ! [ -f "$DTBS_PATTERNS" ]; then
	DTBS_PATTERNS="/usr/share/${PATTERNS_DIR}/${DPKG_MAINTSCRIPT_ARCH}"
fi

rsync \
	--verbose \
	--archive \
	# Put all of the .dtbs directly into the destination, with no extra
	# directories created. u-boot can look in a 'dtbs' subdir, but the Raspberry
	# Pi bootloader cannot (I think, I need to double check).
	--no-relative \
	# Copy real files, not symlinks.
	--copy-links \
	# The filesystem timestamps may lie, so use the checksum for whether or not
	# to skip.
	--checksum \
	# Covered by the "exec" redirect at the top of the script, but just making
	# sure.
	--msgs2stderr \
	# TODO: should this be enabled?
	#--backup-dir=..\
	# Read a list of patterns to include from stdin (from the loop above)
	--include-from="$DTBS_PATTERNS" \
	"$DEVICE_TREE_DIR" \
	"$KERNELDIR"

# The u-boot nodes allow the DTBs to be in a "dtb" subdirectory, but the RPi
# network bootloader doesn't (TODO: double check that), so scattered in the
# kernel directory it is.
case "${VERSION}" in
	*armmp)
		msg_info "Copying BeagleBone device trees"
		cp -f ${DEVICE_TREE_DIR}/am335x-bone*.dtb "${KERNELDIR}/"
		msg_info "Copying Raspberry Pi device trees"
		cp -f ${DEVICE_TREE_DIR}/bcm*.dtb "${KERNELDIR}/"
		# The Fingbox is a slightly modified Orange Pi
		msg_info "Copying H3 Orange Pi device trees"
		cp -f ${DEVICE_TREE_DIR}/sun8i-h3-orangepi-*.dtb "${KERNELDIR}/"
		;;
	*arm64)
		msg_info "Copying Raspberry Pi device trees"
		cp -f ${DEVICE_TREE_DIR}/broadcom/bcm*.dtb "${KERNELDIR}/"
esac