#!/bin/sh

set -e
exec </dev/null >&2

VERSION="$1"
NETBOOTDIR="/boot/netboot/"
FIRMWAREDIR="/usr/lib/raspi-firmware/"

msg_err() {
	echo >&2 "E: cluster-netboot-raspi: $1"
	exit $2
}

msg_warn() {
	echo >&2 "W: cluster-netboot-raspi: $1"
}

msg_info() {
	echo >&2 "I: cluster-netboot-raspi: $1"
}

# I'm not sure why, but DPKG_MAINTSCRIPT_ARCH is "all"...
_CLUSTER_NETBOOT_ARCH="$(dpkg --print-architecture)"

# Violating Debian kernel hook guidelines for bootloaders (sec 8.2 in the
# Debian Linux Kernel Handbook) by exiting with a non-0 status when the
# bootloader is "disabled". In this case, I *want* to be alerted that the
# "bootloader" isn't being updated properly.
if [ ! -d "${NETBOOTDIR}" ]; then
	msg_err "/boot/netboot is not mounted" 3
elif [ ! -w "${NETBOOTDIR}" ]; then
	msg_err "/boot/netboot is not writable" 4
fi

if [ -z "${VERSION}" ]; then
	msg_err "No kernel version given" 2
fi

# Cribbed from the initramfs-tools postinst script.
# This avoids running the script mutliple times (see Debian Policy manual 
# section 6.5 for the various arguments a postrm script can be given).
if [ -n "$DEB_MAINT_PARAMS" ]; then
	# This will clobber the old script parameters, but that's alright as they're
	# already saved.
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

. /usr/share/cluster-netboot/load-config.sh

if [ ! -d "$FIRMWAREDIR" ] || \
		[ ! -r "$FIRMWAREDIR" ] || \
		[ ! -x "$FIRMWAREDIR" ]; then
	msg_warn "${FIRMWAREDIR} is not available, skipping."
	exit 0
fi
msg_info "Copying Raspberry Pi firmware files"
# Just spray the RPi firmware files everywhere as their subdirectory handling is
# a bit lacking.
rsync \
	--checksum \
	--update \
	--msgs2stderr \
	"${FIRMWAREDIR}" \
	"${NETBOOTDIR}"

KERNELDIR="${NETBOOTDIR}/kernel-${VERSION}-${_CLUSTER_NETBOOT_ARCH}"
CURRENT_KERNEL_FILE="current_kernel_${_CLUSTER_NETBOOT_ARCH}.txt"

msg_info "Updating current kernel configuration at ${CURRENT_KERNEL_FILE}"
cat >"${NETBOOTDIR}/${CURRENT_KERNEL_FILE}" <<EOF
# AUTOMATICALLY GENERATED FILE, DO NOT EDIT!
os_prefix=${KERNELDIR}
EOF

msg_info "Copying config.txt to ${NETBOOTDIR}"
CONFIG_TXT="/usr/share/cluster-netboot/raspi-config.txt"
if ! [ -f "${CONFIG_TXT}" ]; then
	msg_warn "Missing '${CONFIG_TXT}'!"
	exit 0
fi
rsync \
	--checksum \
	--msgs2stderr \
	"$CONFIG_TXT" \
	"${NETBOOTDIR}/config.txt"

# Update the RPi command line.
echo "$CLUSTER_RASPI_CMDLINE" > "${NETBOOTDIR}/rpi_cmdline.txt"
