#!/bin/bash

set -euo pipefail

DPKG="/usr/bin/dpkg"
MOUNT="/usr/bin/mount"
UMOUNT="/usr/bin/umount"
MKDIR="/usr/bin/mkdir"
RMDIR="/usr/bin/rmdir"
ID="/usr/bin/id"

function log_exec() {
	echo "$@"
	"$@"
}

# Which arch to upgrade
ARCH="${ARCH:-$(${DPKG} --print-architecture)}"

if [ "$EUID" != "0" ]; then
	echo "This command must be run as root."
	exit 1
fi

. /usr/share/cluster-netboot/load-config.sh
if [ "$CLUSTER_NFS_SERVER" = "" ]; then
	# This command is only safe to run on one of the nodes booted off of the
	# shared root.
	# The net-*.conf files are created in the initramfs during network booting.
	# There *should* only be one, and its contents are options from network
	# setup (like DHCP).
	[ -f /run/net-*.conf ] && . /run/net-*.conf
	if [ "$ROOTSERVER" = "" ]; then
		CLUSTER_NFS_SERVER="${ROOTPATH#:*}"
	else
		CLUSTER_NFS_SERVER="$ROOTSERVER"
	fi
fi

case "$ARCH" in
armhf)
	NFS_ROOT_PATH="$CLUSTER_NFS_ROOT_ARMHF_PATH";;
arm64)
	NFS_ROOT_PATH="$CLUSTER_NFS_ROOT_ARM64_PATH";;
esac

ROOT_DIR="/tmp/recursive_root_${ARCH}"
log_exec $MKDIR "$ROOT_DIR"

log_exec $MOUNT -t nfs -o rw "${NFS_SERVER}:${NFS_ROOT_PATH}" "$ROOT_DIR"

# Mount the various special filesystems
for FS in dev sys proc dev/pts; do
	log_exec $MOUNT --bind /${FS} "${ROOT_DIR}/${FS}"
done

# Mount firmware directories
log_exec $MOUNT -t nfs -o rw "${NFS_SERVER}:${CLUSTER_NFS_NETBOOT_PATH}" ${ROOT_DIR}/boot/netboot
if [ -d /boot/firmware ]; then
	log_exec $MOUNT --bind /boot/firmware ${ROOT_DIR}/boot/firmware
fi

chroot ${ROOT_DIR} /bin/bash

# Now clean up
if [ -d /boot/firmware ]; then
	log_exec $UMOUNT ${ROOT_DIR}/boot/firmware
fi
log_exec $UMOUNT ${ROOT_DIR}/boot/netboot

for FS in dev/pts dev sys proc; do
	if [ -e "${ROOT_DIR}/${FS}" ]; then
		log_exec $UMOUNT "${ROOT_DIR}/${FS}"
	fi
done

log_exec $UMOUNT "$ROOT_DIR"
log_exec $RMDIR "$ROOT_DIR"
