#!/bin/bash

set -e

if ! [ -d /boot/firmware ]; then
	echo "No firmware partition mounted."
	exit 1
fi

if [[ $EUID != 0 ]]; then
	echo "Not running as root"
	exit 1
fi

MODEL_PATH=/proc/device-tree/model

strip_null() {
    sed 's/\(.*\)\x0/\1/' $1
}

MODEL="$(strip_null ${MODEL_PATH})"

RSYNC_OPTS="--checksum --verbose"

case "$MODEL" in
*BeagleBone*|*Beaglebone*)
	echo "Updating BeagleBone firmware"
	# The am335x_evm files are good for all Beaglebone (according to the Debian
	# readme).
	rsync $RSYNC_OPTS /usr/lib/u-boot/am335x_evm/{MLO,u-boot.img} /boot/firmware/
	;;
"Raspberry Pi*")
	echo "Updating Raspberry Pi firmware"
	rsync $RSYNC_OPTS /usr/lib/raspi-firmware/ /boot/firmware/
	(
		case "$MODEL" in
		"Raspberry Pi 2*")
			rsync $RSYNC_OPTS /usr/lib/u-boot/rpi_2/u-boot.bin /boot/firmware/;;
		"Raspberry Pi 3*")
			rsync $RSYNC_OPTS /usr/lib/u-boot/rpi_3_32b/u-boot.bin /boot/firmware/;;
		"Raspberry Pi 4*")
			rsync $RSYNC_OPTS /usr/lib/u-boot/rpi_4_32b/u-boot.bin /boot/firmware/;;
		esac
	)
	;;
esac