#!/bin/sh

if [ -n "$INITRAMFS_TOOLS_KERNEL_HOOK" ]; then
	echo "cluster-netboot: deferring update via initramfs-tools (hook will be called later by the kernel package)"
	exit 0
fi

KERNEL_HOOK=/etc/kernel/postinst.d/z-cluster-netboot
if [ -x "$KERNEL_HOOK" ]; then
	DEB_MAINT_PARAMS=configure $KERNEL_HOOK $1
else
	echo "Unable to execute ${KERNEL_HOOK}"
	exit 1
fi
